manifest:
  remotes:
      # zmk official fork with mouse emulation
    - name: zmkfirmware
      url-base: https://github.com/ftc/
      # bravekarma
    - name: caksoylar
      url-base: https://github.com/caksoylar
      # nice-view-gem
    - name: m165437
      url-base: https://github.com/M165437
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: mouse-ftc 
      import: app/west.yml
    - name: nice-view-gem
      remote: m165437
      revision: main
  self:
    path: config
